-- ============================================
-- AquaSearch Initial Schema
-- ============================================


-- ============================================
-- 1. shops
-- 크롤링 대상 쇼핑몰
-- ============================================

create table shops (
    id bigint generated by default as identity primary key,
    name text not null,
    url text not null unique,
    address text
);


-- ============================================
-- 2. categories
-- 사이트의 탐색용 카테고리
-- ============================================

create table categories (
    id bigint generated by default as identity primary key,
    name text not null,
    parent_id bigint references categories(id)
);

create index idx_categories_parent_id
    on categories(parent_id);

create unique index uq_categories_parent_name
    on categories(parent_id, name);


-- ============================================
-- 3. search_groups
-- AquaSearch가 정의하는 검색용 그룹
-- ============================================

create table search_groups (
    id bigint generated by default as identity primary key,
    name text not null,
    thumbnail_url text,
    category_id bigint references categories(id)
);

create index idx_search_groups_category_id
    on search_groups(category_id);


-- ============================================
-- 4. search_terms
-- 검색 그룹의 검색어 / 별명 사전
-- ============================================

create table search_terms (
    id bigint generated by default as identity primary key,
    search_group_id bigint not null references search_groups(id),
    term text not null
);

create index idx_search_terms_term
    on search_terms(term);

create unique index uq_search_terms_group_term
    on search_terms(search_group_id, term);


-- ============================================
-- 5. shop_products
-- 실제 쇼핑몰에서 크롤링한 상품
-- ============================================

create table shop_products (
    id bigint generated by default as identity primary key,

    shop_id bigint not null references shops(id),

    search_group_id bigint references search_groups(id),

    name text not null,

    status text not null default 'available',

    price bigint,

    product_url text not null,

    image_url text,

    last_crawled_at timestamptz not null default now()
);

create index idx_shop_products_shop_id
    on shop_products(shop_id);

create index idx_shop_products_search_group_id
    on shop_products(search_group_id);

create index idx_shop_products_price
    on shop_products(price);